import { defineStore } from "pinia";
import { SetupStoreId } from "@/enum";
import useBoolean from "@/hooks/use-boolean";
import { createStaticRoutes, getAuthVueRoutes } from "@/router/routes";
import { ref, shallowRef } from "vue";
import type { ElegantConstRoute } from "@elegant-router/types";
import type { RouteRecordRaw } from "vue-router";
import { router } from "@/router";

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const { bool: isInitConstantRoute, setBool: setIsInitConstantRoute } =
    useBoolean();

  /** constant routes */
  const constantRoutes = shallowRef<ElegantConstRoute[]>([]);
  /** auth routes */
  const authRoutes = shallowRef<ElegantConstRoute[]>([]);

  const removeRouteFns: (() => void)[] = [];
  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE);

  function addRoutes(routes: ElegantConstRoute[]) {
    const constantRoutesMap = new Map<string, ElegantConstRoute>([]);

    routes.forEach((route) => {
      constantRoutesMap.set(route.name, route);
    });

    constantRoutes.value = Array.from(constantRoutesMap.values());
  }

  /** init constant route */
  async function initConstantRoute() {
    if (isInitConstantRoute.value) return;

    const staticRoute = createStaticRoutes();

    if (authRouteMode.value === "static") {
      addRoutes(staticRoute.constantRoutes);
    } else {
      // const { data, error } = await fetchGetConstantRoutes();
      // if (!error) {
      //   addRoutes(data);
      // } else {
      //   // if fetch constant routes failed, use static constant routes
      //   addRoutes(staticRoute.constantRoutes);
      // }
    }

    handleConstantAndAuthRoutes();

    setIsInitConstantRoute(true);

    // tabStore.initHomeTab();
  }

  /** handle constant and auth routes */
  function handleConstantAndAuthRoutes() {
    const allRoutes = [...constantRoutes.value, ...authRoutes.value];

    // const sortRoutes = sortRoutesByOrder(allRoutes);

    const vueRoutes = getAuthVueRoutes(allRoutes);

    // resetVueRoutes();

    addRoutesToVueRouter(vueRoutes);

    // getGlobalMenus(sortRoutes);

    // getCacheRoutes(vueRoutes);
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach((route) => {
      const removeFn = router.addRoute(route);
      addRemoveRouteFn(removeFn);
    });
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn);
  }

  return {
    isInitConstantRoute,
    initConstantRoute,
  };
});
